spring.application.name=eventos
spring.datasource.url=jdbc:mysql://localhost/eventos?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=VMk2007@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sq1=true
